version: '2'


services:
  goserver:
    container_name: intraner_webserver
    build: ./server
    environment:
      - VIRTUAL_HOST=iapi.lempls.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=iapi.lempls.com
      - LETSENCRYPT_EMAIL=flamecze@gmail.com
    networks:
         - default
         - web-net

networks:
  default:
  web-net:
    external:
      name: web-net
