version: '2'

services:
  goserver:
    container_name: intranet_backend
    build: .
    environment:
      - VIRTUAL_HOST=iapi.lempls.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=iapi.lempls.com
      - LETSENCRYPT_EMAIL=flamecze@gmail.com
    networks:
         - web-net

networks:
  web-net:
    external:
      name: web-net
